// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irpdufnkovuwtpcvfjht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlycGR1Zm5rb3Z1d3RwY3Zmamh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTY1ODQsImV4cCI6MjA2MjY5MjU4NH0.8NuTqUqcU48Cpp_7rPPC5igKZjjgYDRdKQftCrWD-UU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);